# Create Map of world space # = wall block, . = space,  p = player position facing south
map_two = []
map_two.append(list('################'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#.......p......#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('#..............#'))
map_two.append(list('################'))