# Create Map of world space # = wall block, . = space, p = player position facing south
map_one = []
map_one.append(list('################'))
map_one.append(list('#..............#'))
map_one.append(list('#.......########'))
map_one.append(list('#..........p...#'))
map_one.append(list('#......##......#'))
map_one.append(list('#......##......#'))
map_one.append(list('#..............#'))
map_one.append(list('###............#'))
map_one.append(list('##.............#'))
map_one.append(list('#......####..###'))
map_one.append(list('#......#.......#'))
map_one.append(list('#..............#'))
map_one.append(list('#..............#'))
map_one.append(list('#......#########'))
map_one.append(list('#..............#'))
map_one.append(list('################'))