matrix_glyph = []
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))
matrix_glyph.append(list('                                '))


matrix_color = []
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('RRRRRRRWRRRRRRRWRRRRRRRWRRRRRRRW'))
matrix_color.append(list('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))
matrix_color.append(list('RRRWRRRRRRRWRRRRRRRWRRRRRRRWRRRR'))